"""make fields geo_class, geo_type and importance nullable

Revision ID: 24d1261a9528
Revises: ee75ff5c2e97
Create Date: 2024-04-21 17:52:40.867063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d1261a9528'
down_revision = 'ee75ff5c2e97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('geo_point', 'geo_class',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('geo_point', 'geo_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('geo_point', 'importance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('geo_point', 'importance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('geo_point', 'geo_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('geo_point', 'geo_class',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
