"""create_table_geo_point

Revision ID: 0f59cca3bf9e
Revises: 
Create Date: 2024-04-21 16:36:19.960805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f59cca3bf9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.String(length=255), nullable=False),
    sa.Column('lon', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=1024), nullable=False),
    sa.Column('_class', sa.String(length=64), nullable=False),
    sa.Column('_type', sa.String(length=64), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geo_point')
    # ### end Alembic commands ###
