"""change _class, _type to geo_class, geo_type

Revision ID: ee75ff5c2e97
Revises: 0f59cca3bf9e
Create Date: 2024-04-21 17:32:08.416927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee75ff5c2e97'
down_revision = '0f59cca3bf9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geo_point', sa.Column('geo_class', sa.String(length=64), nullable=False))
    op.add_column('geo_point', sa.Column('geo_type', sa.String(length=64), nullable=False))
    op.drop_column('geo_point', '_class')
    op.drop_column('geo_point', '_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geo_point', sa.Column('_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('geo_point', sa.Column('_class', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('geo_point', 'geo_type')
    op.drop_column('geo_point', 'geo_class')
    # ### end Alembic commands ###
